services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Wake@2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    restart: always
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./.docker/sqlserver/create-database.sql:/tmp/create-database.sql
      - ./.docker/create-database.sh:/tmp/create-database.sh
    command: /bin/bash ./tmp/create-database.sh